const text = {
  "intro": "Antichitatea este perioada este perioada istorică cuprinsă între apariția scrierii și până când în începe Evul Mediu. În acea perioadă, civilizația greacă și cea romană s-au dezvoltat în regiunea Mării Mediterane. Atât în Grecia Antică, precum și în Imperiul Roman existau atât orașe mari, dar și așezări rurale. În acea epocă, oamenii au descoperit multe invenții, iar unele dintre ele le folosim și astăzi, evident, mult îmbunătățite. Spre exemplu, a fost inventată o formă inițială a betonului, piscinile încălzite, democrația, dar și un fel de ziar. Singura diferență era că, în loc să fie tipărite pe hârtie, știrile erau cioplite în bucăți mari de piatră.",
  "text-1": "Arheologii sunt cei care ne-au oferit toate informațiile pe care le avem despre Timișoara din vremurile antice. Astfel, știm că, în acea epocă, din partea vestică a Europei, aici au venit mai multe comunități celtice.",
  "text-2": "Din perioada în care, pe o parte a teritoriului actual al României, exista Regatul Dac, nu sunt foarte multe date despre cei care trăiau pe malul râului Bega. Abia după ce dacii sunt cuceriți de romani, apar mai multe date despre această zonă. Se pare că unul dintre cei mai importanți împărați ai Imperiului Roman, Marcus Aurelius, plănuia să înființeze provincia Sarmația în regiune, pentru că aici locuiau triburi de sarmați.",
  "text-3": "La periferiile Timișoarei, arheologii au descoperit așezări din perioada antică. Astfel în zona Freidorf și în apropierea localității Dumbrăvița, dar și pe unul dintre terenurile care aparține Universității de Științe Agricole din Timișoara, specialiștii au găsit dovezi clare care arată că, în epoca antică, aici s-au dezvoltat mici comunități.",
  "text-4": "Atunci, ca și acum, apa era foarte importantă pentru oameni, așa că, locuitorii Câmpiei Banatului trăiau în sate deschise, nefortificate, amplasate pe terase cu panta lină, în apropierea surselor de apă.",
  "text-5": "Arheologii au descoperit că locuințele erau construite din lemn sau cu pereți din nuiele împletite, tencuiți cu lut, precum și bordeie. Acestea erau înconjurate de gropi pentru păstrarea proviziilor, gropi de gunoi, vetre de foc și cuptoare menajere (foarte rar poziționate în interiorul locuințelor). Nu în ultimul rând, specialiștii au fost norocoși să descopere la Cioreni o fântână.",
  "text-6": "Oamenii din zonă se ocupau în special cu creșterea animalelor, dar și cu agricultura practicată pe terenurile din apropiere. O astfel de economie permitea asigurarea nevoilor proprii ale fiecărei comunități.",
  "text-7": "Descopeirea râșnițelor de piatră precum și urme ale unor semințe de cereale carbonizate, indică faptul că se consumau foarte multe cereale. Oasele de animale aflate în decursul săpăturile arheologice demonstrează faptul că ocupația de bază în acest areal era creșterea animalelor, în special vite și cai, dar erau consumate și oi, capre sau porci. Cornutele de talie mare (boi, vaci) erau crescute nu doar pentru produsele animale, cât și pentru muncile agricole sau transport.",
  "text-8": "În ceea ce privește meșteșugurile practicate în antichitate în zona Timișoarei, la Freidorf  au fost funcționat ateliere de olărie care asigurau necesarul de recipiente pentru comunitatea respectivă, fiind documentate arheologic câteva cuptoare de ars vase ceramice.",
  "text-9": "Oalele rezultate se aseamănă atât cu produsele ceramice din Dacia romană, cât și cu vasele din zona extracarpatică sau de la nord de granița Imperiului.",
  "text-10": "Alte mici ateliere funcționau la Freidorf și Cioreni pentru prelucrarea metalelor.",
  "text-11": "În respectivele așezări au fost găsite mai multe creuzete de mici dimensiuni, recipiente din lut care erau utilizate în cadrul diverselor procedee metalurgice.",
  "text-12": "Prelucrarea osului și cornului reprezintă o altă îndeletnicire a locuitorilor din așezările menționate. Din aceste materii prime se confecționau diverse obiecte de uz comun, precum piepteni, mânere de cuțite, ace de cusut. În strânsă legătură cu ultima categorie de piese, trebuie menționat meșteșugul torsului și țesutului, ilustrat și prin descoperirile de fusaiole (mici greutăți ceramice pentru fus) și de greutăți din lut folosite la războiul de țesut vertical."
}

export default { text };