const text = {
  "intro": "Care este povestea Timișoarei în Evul Mediu? Hmmm...ce este Evul mediu? Este o perioadă istorică ce a durat aproape 1000 de ani. În Evul mediu, oamenii s-au plimbat mult, au explorat noi teritorii și așa au apărut popoarele migratoare. În cei aproape 1000 de ani au fost războaie peste tot în Europa. Tot atunci au apărut regii și regatele, adică țările conduse de regi.",
  "text-1": "Timișoara, care se numea atunci Temesvar, era parte a Regatului Ungariei.",
  "text-2": " Evident, orașul așa cum îl cunoaștem astăzi, nu exista. Erau mai multe insule pe care oamenii și-au construit case. Practic, erau vreo 20 de case și aproape 200 de locuitori în toată așezarea. Insulele au fost formate de brațele râurilor Bega și Timiș. Pe cea mai mare dintre insule a fost construită o cetate din chirpici. Adică, cărămizi de pământ amestecat cu apă și paie.",
  "text-3": "În Evul Mediu oamenii au trăit fără supermarket și fără fast food. Mâncau ce cultivau prin grădini și animalele pe care le creșteau în curți. Nu era cool să faci baie, iar, săpunul, așa cum îl știm azi, nu era încă inventat. Foloseau plante ca să trateze orice boală, iar când era mai grav adăugau lipitori în tratament. Pentru că Timișoara era înconjurată de ape, erau foarte mulți țânțari, iar oamenii se îmbolnăveau frecvent de malarie.",
  "text-4": "Prin anul 1300 a avut loc un fel de joc de strategie între do nobili, Otto de Bavaria și Robert de Anjou.",
  "text-5": "Aceștia trebuiau să-și arate talentul de negociator, iar cel care aduna mai mulți aliați urma să fie regele Ungariei. Robert a venit la Timișoara ca să-și construiască aici o bază și să își caute aliați. A poruncit să fie ridicată o cetate mai mare și puternică decât cea existentă. Robert de Anjou era priceput la negociere, așa că, într-un final, câștigă, devine regele Ungariei, iar, Timișoara, capitala acestui regat. Între timp, s-a dus vorba în toată Europa că la Timișoara e fain, așa că au venit aici oameni de pe tot continentul. A crescut numărul locuitorilor și s-au construit muuuulte case.",
  "text-6": "După ce așezarea s-a dezvoltat, Robert de Anjou s-a mutat la Buda – în jumătatea care formează astăzi orașul Budapesta",
  "text-7": "La aproape 100 de ani de la plecarea lui Robert de Anjou, la Timișoara ajunge Ioan de Hunedoara.",
  "text-8": "El era un fel de prinț al Transilvaniei, și, pentru că avea această funcție, era și căpetenia Timișoarei. Poruncește ca vechiul palat din cetate să fie fortificat. Era preocupat de siguranța orașului, așa că, aduce tunuri în cetate și ordonă să fie ridicate ziduri de apărare.",
  "text-9": "Cetatea Timișoarei devenea din ce în ce mai puternică. În jurul ei se dezvolta orașul și se nășteau tot mai multe povești.",
  "text-10": "O poveste interesantă este cea a lui Pavel Cnezul, un alt conducător important al comitatului Timiș.",
  "text-11": "Pavel Cnezul este cunoscut şi ca Pavel Chinezul, fără să aibă vreo legătură cu China. A intrat în armată ca simplu militar, dar pentru că era curajos și se pricepea la strategie (nu jucase jocuri de strategie!) a ajuns rapid căpitan general și mai apoi comite, adică conducătorul întregului teritoriu în vremea regelui Mathia Corvinul. Oricum, conducea armatele din regiunea în care se găsea Timișoara și a reușit să-i învingă de multe ori pe otomani.",
  "text-12": "Legenda spune că era atât de puternic că putea să ducă la subsioară doi turci deodată (cam cum ar ridica cineva la sală gantere!). Câtă vreme Pavel Chinezul a fost conducătorul armatelor regatului, periculoșii turci n-au putut intra în Timișoara. Dar, aflăm mai multe despre otomani, adică turcii de azi, când povestim despre cum au cucerit ei cetatea Timișoarei."
}

export default { text }