const text = {
  "intro": "Otoman nu este numele unui peşte exotic, este numele unui mare imperiu, condus de un sultan care avusese un vis: se făcea că era un copac mare, mare, cu umbra maaare, mare care se întindea peste toată lumea. Când s-a trezit din vis, sultanul, a înţeles că imperiul său este copacul şi că el va cuprinde întreaga lume!",
  "text-1": "Sultanul locuia departe, la Istanbul, în palatul său, un loc minunat cu multe camere şi cu grădini splendide. Conducătorii de pe cuprinsul Imperiului erau chemaţi de către sultan să se prezinte la „Pragul fericirii noastre”.",
  "text-2": "Otomanii se rugau lui Allah, în locuri speciale, numite moschei şi geamii. Ele aveau un turn înalt numit minaret, de unde un muezin chema poporul la rugăciune.",
  "text-3": "La aproape 100 de ani de când primul sultan visase copacul cel mare, urmaşul său, sultanul Suleyman Magnificul a vrut să cucerească şi Timişoara, să fie şi acest oraş la umbra copacului său, astfel că a încercat iar şi iar, până când a reuşit!",
  "text-4": "Timişoara a fost cucerită de turci în vara lui 1552.",
  "text-5": "Se povesteşte că a fost o vară caldă, atât de caldă încât broaştele din mlaştinile din jurul oraşului îşi căutau casă nouă în fântânile încă umede.",
  "text-6": "Din tabăra turcească, întinsă ca marea, din afara zidurilor de curând renovate, se auzeau porunci scurte. Din cortul său, Ahmed paşa, al doilea vizir al sultanului Suleyman Magnificul, poruncea curierilor să trimită 'ghiaurilor demni de Infern' (adică soldaţilor creştini) de dincolo de ziduri mesaje prinse de săgeţi ca trupele timişorene să se predea.",
  "text-7": "Înăuntrul zidurilor, ştiau cu toţii, soldaţi şi locuitori ai oraşului că oastea creştină de 3000 de soldaţi nemţi, spanioli, polonezi, maghiari şi români nu putea să ţină sub ziduri prea mult timp armata otomană cu cele 16 tunuri ale sale, care ataca din şapte părţi.",
  "text-8": "În noaptea aceea de iulie ai fi putut face plajă de atâta căldură. Ştefan Lossonczy, comandantul trupelor din Timişoara, şi el comite de Timiş şi comandant general al Părţilor Inferioare ale Regatului, la fel ca şi Pavel Chinezul, obosit după o lună de lupte, răspunse afirmativ cererii de predare. Ahmed paşa îi promisese că-i va lăsa în viaţă pe cei ce se predau. În ceaţa dimineţii, la poarta cetăţii, un lung şir de ostaşi, în frunte cu Lossonczy însuşi, înfrunta fără cai, săbii ori armură, pe Ahmed. Vizirul însă nu s-a ţinut de cuvânt! Comandantul a fost decapitat, iar supravieţuitorii, măcelăriţi de ieniceri.",
  "text-9": "Oraşul Timişoara cu grădinile sale frumoase de trandafiri, cu râul dătător de viaţă, era astfel la umbra copacului din vis. A fost pustiu oraşul în timpul turcilor? Au fugit cu toţii? Au fost numai turci? Nuuuu, nici gând! După şocul pierderii cetăţii, viaţa a trebuit să continue!",
  "text-10": "Începând din acel iulie torid, timp de 164 de ani, locuitorii au avut o experienţă nouă, cu oameni noi care vorbeau într-o altă limbă şi purtau turban în loc de pălărie, care au adus cu ei cafeaua, orezul, moschea, baclavaua dar şi cuvintele ciubuc (pipă), rachie (raki), sarma.",
  "text-11": "Cetatea, ca o broască ţestoasă cu picioarele în mlaştină, era condusă de acum de un paşă. Unele biserici au fost transformate în moschei, cum a fost biserica Sf. Gheorghe. S-au construit patru geamii, adică moschei mai mari. După modelul din Turcia, otomanii au construit băi publice, care semănau cu de spa-urile de astăzi. Pentru că nu exista asfalt, au pavat străzile cu bârne de lemn, să nu se umple roţile căruţelor cu noroi, căci altfel şi un elefant s-ar fi putut împotmoli!",
  "text-12": "În această vreme, Timişoara a avut 400 de magazine dar şi cafenele, căci turcii erau maaari consumatori de cafea şi de tutun, cu toate că nu este sănătos, dar ei nu ştiau asta!",
  "text-13": "Dar locul cel mai interesant şi aglomerat era piaţa, numită bazar. Acolo, negustorii din Orient s-au întâlnit cu cei din Occident: italieni, vienezi, ardeleni şi polonezi; acolo ai fi putut vedea fructe nemaiîntâlnite, haine deosebite şi încălţări din piele roşie, blănuri de animale cu nume ciudate, alimente şi condimente apetisante şi jucării de porţelan.",
  "text-14": "Din păcate, locuitorii celor peste 1500 de case ale Timişoarei, nu erau prea ecologişti, aruncau toate gunoaiele în râul Timiş. Apă se lua tot din râu, căci nu era la robinet.",
  "text-15": "Ce mâncau timişorenii în timpul turcilor?",
  "text-16": "Plăcinte cu miere şi turtă cu unt pentru copiii cuminţi, ciorbă neagră, dacă nu erai cuminte. Putea primi şi varză ori dovleac umplut. Dacă erai sărac, o pâinişoară numită ţipău (din cuvântul maghiar 'czipo') şi o bucată de brânză. Dacă îţi creşteai în grădină, aveai de mâncare varză, linte sau mazăre. Carnea la mare căutare era cea de miel, de oaie sau de pasăre, gătită în combinaţii şi feluri neaşteptate. Şi peştele era la mare căutare. ",
  "text-17": "Vara, în grădinile din jur, sau cumpărate de la târgoveţi, fructele aveau mare trecere: vişine, fragi, prune şi pere. Peste tot se găsea mied, o băutură dulceagă, cam ca un sirop de tuse, puţin acidulată, făcută din miere. Şi berea era cunoscută şi băută de toată lumea. Aromată cu ghimbir ori cu plante din grădină, nu avea gustul celei pe care o beau oamenii astăzi!",
  "text-18": "Şi din bucătăria otomană am preluat câte ceva: sarmalele, pilaful, reţete pentru carne tocată şi feluri multe de plăcinte cu foi îndulcite şi aromate şi fructe date prin miere (zahărul nu fusese încă descoperit).",
  "text-19": "Se îmbrăcau frumos timişorenii?",
  "text-20": "Fără să aibă magazine de modă ori fabrici de haine, oamenii ca noi purtau haine de pânză. Iarna mai adăugau şi haine de lână. Bărbaţii aveau un fel de pantaloni largi, prinşi cu copci în lateral. La genunchi, pantalonii aveau câte o bucată de piele fină de capră, cam aşa, cum avem noi genunchiere pentru bicicletă! Cămaşa de pânză, pieptarul şi căciula colorată, tot de pânză mai groasă, completau outfit-ul. În picioare purtau papuci groşi, din piele de vacă.",
  "text-21": "Femeile purtau părul strâns sub bonetă, la piaţă, la biserică, dar şi acasă. Ele îşi puneau un şorţ peste rochia din pânză colorată, prins cu cordon. Pentru că nu aveau poştete, de un alt cordon îşi prindeau săculeţul cu bani şi cheile de la casă. Nelipsit era şalul, din pânză, din lână, dat peste umeri.",
  "text-22": "Copiii erau îmbrăcaţi ca nişte adulţi mai mici.",
  "text-23": "Poveste scrisă de Dr. Livia Magina"
}

export default { text };