const text = {
  "intro": "Imaginează-ți că te plimbi cu tramvaiul prin Timișoara anului 1918.",
  "text-1": "Te urci în tramvai în Piața Traian și călătorești spre centrul orașului. În primul rând, observi că în jurul tău puțini oameni vorbesc limba română. Te întrebi:",
  "text-2": "-Oare unde mă aflu?",
  "text-3": "-Temesvar, Temeschwar, Temišvar…îți vor răspunde ceilalți pasageri.",
  "text-4": "Răspunsurile în diverse limbi reprezintă fiecare dintre naționalitățile conlocuitoare ale Timișoarei în perioada respectivă. Nu sunt turiști veniți în Timișoara să vadă distrugerile provocate de Primul Război Mondial, ci maghiari, germani și sârbi, cu toții locuitori ai Timișoarei de-a lungul câtorva secole.",
  "text-5": "Ultimul recensământ realizat de către Imperiul Austro-Ungar în anul 1910, stat european multinațional, care includea și Timișoara între granițele sale, menționează că orașul avea aproximativ 72.500 de locuitori, însă din totalul populației doar 10% era reprezentată de români. După 10 ani, în anul 1920, primul recensământ realizat în Banat și Transilvania, evidențiază o populație de 82.689 locuitori, dintre care 20% erau români. În anul 1930, în cadrul primului recensământ realizat în România Mare, populația Timișoarei era deja de 102.390 de locuitori, dintre care 25% erau români.",
  "text-6": "Deși se observă o creștere semnificativă a populației de origine română în oraș, germanii reprezentau în continuare peste 30% din totalul locuitorilor Timișoarei interbelice (perioada cuprinsă între cele două războaie mondiale). Acestora li se alăturau maghiarii, cu un procentaj asemănător. Nu în ultimul rând, în Timișoara interbelică conviețuiau și comunități importante de sârbi, bulgari, ucrainieni și cehi. Toți au influențat dezvoltarea laturii multiculturale a orașului.",
  "text-7": "În ceea ce privește istoria, un eveniment care a marcat evoluția orașului a fost intrarea armatei române, la data de 3 august 1919, în Timișoara, în Piața Unirii de astăzi, denumire dedicată acestui moment istoric, moment care a schimbat rolul și evoluția orașului în spațiul carpato-danubiano-pontic.",
  "text-8": "Primul primar român al orașului a fost inginerul Stan Vidrighin, ales la 1 septembrie 1919. Acesta a fost extrem de apreciat de către locuitorii orașului deoarece proiectele sale, printre care introducerea apei potabile și construcția sistemului de canalizare, au avut un impact pozitiv asupra vieții fiecăruia dintre ei.",
  "text-9": "Pe parcursul perioadei interbelice, orașul s-a dezvoltat sub toate aspectele. Pe plan economic, industria se dezvoltă, fiind construite întreprinderi noi, în timp ce se extind și cele care existau deja în oraș.",
  "text-10": "De exemplu, prima fabrică de spirt din Timișoara se transformă în întreprindere chimică, numindu-se ,,Solventul’’.",
  "text-11": "Fabrica de ciocolată ,,Kandia’’ producea o varietate de dulciuri precum bomboane, drajeuri, ciocolată, spre bucuria copiilor din întreaga țară.",
  "text-12": "În același timp, sunt înființate instituții bancare, comerțul înflorește, iar mijloacele de transport se diversifică.",
  "text-13": "În Timișoara dintre cele două războaie mondiale funcționau aproximativ 30 de școli, cu predare în limba fiecărei naționalități din oraș. Alături de învățământul preuniversitar, în anul 1920 este înființată prima instituție de învățământ superior, ,, ȘcoalaPolitehnică din Timișoara’’, prin decret semnat chiar de către regale Ferdinand I.",
  "text-14": "Cultura a fost sprijinită și de publicarea cotidiană sau săptămânală a ziarelor în limba maghiară, germană, sârbă și română.",
  "text-15": "Spre sfârșitul perioadei intebelice, în anul 1936, a început construcția Catedralei Mitropolitane din Timișoara, un monument reprezentativ pentru oraș.",
  "text-16": "De asemenea, activitățile sportive prind contur, oamenii practicând sporturi precum fotbal, rugby, baschet sau oina. Astfel, în urmă cu exact 100 de ani, în 1920, apare clubul de fotbal al Politehnicii, echipa Poli de aztăzi, în timp ce echipa de fotbal 'Chinezul Timișoara' obține primul titlu de campioană națională a României în 1921. Nu în ultimul rând, prima echipă profesionistă de fotbal din România a fost 'Ripensia Timișora'.",
  "text-17": "Din punct de vedere administrativ, în cea mai mare parte a perioadei interbelice, Timișoara era reședința județului Timiș-Torontal, fiind o subdiviziune a acestuia, numită 'Plasa Timișoara' sau 'Plasa Centrală'.",
  "text-18": "Orașul era format din cinci cartiere reprezentative: Cetate, Fabric, Elisabetin, Iosefin și Mehala, ultimele două fiind două comune adăugate mai târziu orașului. Multe dintre cartierele de astăzi ale orașului erau și ele commune rurale în perioada interbelică: Freidorf, Fratelia, Ciarda Roșie.",
  "text-19": "În concluzie, perioada interbelică a avut um impact pozitiv asupra evoluției orașului și asupra dezvoltării sale, multiculturalismul, industria, comerțul fiind constant elemente care și-au găsit rolul și locul într-o comunitate în continuă schimbare."
}

export default { text };